/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;

/**
 *
 * @author 55629
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form cadproduto
     */
    public Menu() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnCadastrarEntrada = new javax.swing.JButton();
        BtnBuscarEntrada = new javax.swing.JButton();
        BtnEditarEntrada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText(" Gestão de Entradas");

        BtnCadastrarEntrada.setBackground(new java.awt.Color(204, 204, 255));
        BtnCadastrarEntrada.setText("Cadastrar Entrada");
        BtnCadastrarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarEntradaActionPerformed(evt);
            }
        });

        BtnBuscarEntrada.setBackground(new java.awt.Color(0, 153, 153));
        BtnBuscarEntrada.setText("Buscar Entrada");
        BtnBuscarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarEntradaActionPerformed(evt);
            }
        });

        BtnEditarEntrada.setBackground(new java.awt.Color(0, 51, 204));
        BtnEditarEntrada.setText("Editar Entrada");
        BtnEditarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(BtnCadastrarEntrada)
                        .addGap(47, 47, 47)
                        .addComponent(BtnBuscarEntrada)
                        .addGap(44, 44, 44)
                        .addComponent(BtnEditarEntrada))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCadastrarEntrada)
                    .addComponent(BtnBuscarEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnEditarEntrada))
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>                        

    private void BtnCadastrarEntradaActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void BtnBuscarEntradaActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        dispose();
        new BuscarEntrada().setVisible(true);
    }                                                

    private void BtnEditarEntradaActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JButton BtnBuscarEntrada;
    private javax.swing.JButton BtnCadastrarEntrada;
    private javax.swing.JButton BtnEditarEntrada;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration                   
}
