@startuml

package modelo #e2d6d3 {
    class Usuario {
        - nome : String
        - login : String
        - senha : String
    }

    class Fornecedor {
        - id : int
        - nome : String
        - telefone : String
        - cnpj : String
        - email : String
    }

    class Estoque {
        - quantidade : double
    }

    class Entrada {
        - id : int
        - data : date
        - quantidade : int
        - precoCusto : double
        - produto : Produto
        - fornecedor : Fornecedor
        - lote : String
        - validade : date
        + Entrada(Produto)
    }


    class Saida {
        - id : int
        - produto : Produto
        - data : date
        - desconto : double
        - tipoSaida : String
        + Saida(Produto)
    }

    abstract class Produto {
        - id : int
        - nome : String
        - descricao : String
        - criadoEm : date
        - atualizadoEm : date
    }

    class Mercadoria extends Produto {
        - quantidadeMinima : double
        - porcentagemLucro : double
        - perecivel : boolean
    }

    class Servico extends Produto {
        - garantia : String
    }
}

package dao #b6b1ac {
    class Conexao {
        + {static} SERVIDOR : String
        + {static} USUARIO : String
        + {static} SENHA : String
        + getConexao() : Connection
    }

    note right of Conexao::SERVIDOR
      Atributo com modificadores
      **static**(sublinhado)
      e **final** (maiúsculo).
    end note

    class UsuarioDAO {
        + autenticar(String login, String senha) : Usuario
    }

    class FornecedorDAO {
        + buscar(String nome, boolean status) : Lista Fornecedor
        + buscar(String cnpj, boolean status) : Fornecedor
        + buscar(int id, boolean status) : Fornecedor
        + buscar(Produto produto, boolean status) : Lista Fornecedor
        + salvar(Fornecedor) : Fornecedor
        + alterarStatus(Fornecedor) : boolean
    }

    class EstoqueDAO {
        + getQuantidade(Produto) : double
    }

    class EntradaDAO {
        + buscar(Produto) : Lista Entrada
        + buscar(Fornecedor) : Lista Entrada
        + buscar(date inicio, date final) : Lista Entrada
        + salvar(Entrada) : Entrada
        + alterarStatus(Entrada) : boolean
    }

    class SaidaDAO {
        + buscar(Produto) : Lista Saida
        + buscar(String tipo) : Lista Saida
        + buscar(date inicio, date final) : Lista Saida
        + salvar(Saida) : Saida
        + alterarStatus(Saida) : boolean
    }

    class ProdutoDAO {
        + buscar(String nome, boolean status) : Lista Fornecedor
        + buscar(int id, boolean status) : Produto
        + alterarStatus(Produto) : boolean
        + salvar(Produto) : Produto
    }
}

package view #d0c4b9 {
}

package controlador #abb4bb {
}

@enduml
